from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import date, datetime
from uuid import UUID

# --- Database Models (Mirroring Supabase Tables) ---

class OrdemPedido(BaseModel):
    id: Optional[UUID] = None
    nome_cliente: str
    numero_pedido: int
    data_pedido: date
    preco_total: float
    previsao_entrega: date  # Data prevista da entrega (obrigatório)
    data_entrega: Optional[date] = None  # Data real da entrega (preenchida quando entregue)
    icms: float
    status: str
    codigo_op: str

class Peca(BaseModel):
    id_peca: Optional[UUID] = None
    codigo_op: str
    nome_peca: str
    quantidade: int
    status: str
    nome_cliente: str
    previsao_entrega: date  # Data prevista da entrega
    data_entrega: Optional[date] = None  # Data real da entrega (quando entregue)
    pecas_produzidas: int
    preco_unitario: float

class AlertaAtraso(BaseModel):
    id: Optional[UUID] = None
    nome_cliente: str
    previsao_entrega: date  # Data prevista para cálculo de atraso
    codigo_op: str
    criado_em: Optional[datetime] = None
    nome_peca: str

# --- API Input Models ---

class OrderCreate(BaseModel):
    nome_cliente: str
    numero_pedido: int
    data_pedido: Optional[date] = None
    preco_total: float
    previsao_entrega: date  # Data prevista da entrega (obrigatório)
    data_entrega: Optional[date] = None  # Data real da entrega (preenchida quando entregue)
    icms: float = 0.0
    # codigo_op will be generated by backend
    # status defaults to 'Pendente'

class PartCreate(BaseModel):
    nome_peca: str
    quantidade: int
    preco_unitario: float
    # Other fields inherited from Order or defaults

class PartsListCreate(BaseModel):
    codigo_op: str
    pecas: List[PartCreate]

# --- Catalog Models ---

class TipoItemCatalogo:
    """Tipos de itens disponíveis no catálogo"""
    PRODUTO_FINAL = "Produto Final"
    CONSUMIVEL = "Itens Consumíveis"
    MATERIA_PRIMA = "Matérias Primas"
    INVENTARIO = "Inventário"
    
    @classmethod
    def all_types(cls):
        return [cls.PRODUTO_FINAL, cls.CONSUMIVEL, cls.MATERIA_PRIMA, cls.INVENTARIO]

class CatalogoItem(BaseModel):
    """Modelo para itens do catálogo (tabela: catalogo_pecas)"""
    id: Optional[UUID] = None
    nome: str
    preco: float
    tipo: str  # Produto Final, Itens Consumíveis, Matérias Primas, Inventário
    tempo_producao: Optional[int] = None  # Apenas para Produto Final (em minutos/horas)
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class CatalogoItemCreate(BaseModel):
    """Modelo para criação de itens no catálogo"""
    nome: str
    preco: float
    tipo: str  # Produto Final, Itens Consumíveis, Matérias Primas, Inventário
    tempo_producao: Optional[int] = None  # Obrigatório apenas para Produto Final

# --- Stock Models (Estoque) ---

class EstoqueItem(BaseModel):
    """Modelo para itens do estoque (tabela: estoque)"""
    id: Optional[UUID] = None
    nome: str
    quantidade: int
    preco_unitario: float
    tipo: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class EstoqueItemCreate(BaseModel):
    """Modelo para adicionar/atualizar item no estoque"""
    nome: str
    quantidade: int
    # preco_unitario e tipo são herdados do catálogo

class EstoqueItemUpdate(BaseModel):
    """Modelo para atualizar quantidade no estoque"""
    quantidade: int
    operacao: str = "set"  # "set" = definir valor, "add" = somar, "subtract" = subtrair
