from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import date, datetime
from uuid import UUID

# --- Database Models (Mirroring Supabase Tables) ---

class OrdemPedido(BaseModel):
    id: Optional[UUID] = None
    nome_cliente: str
    numero_pedido: int
    data_pedido: date
    preco_total: float
    data_entrega: date
    icms: float
    status: str
    codigo_op: str
    previsao_entrega: date

class Peca(BaseModel):
    id_peca: Optional[UUID] = None
    codigo_op: str
    nome_peca: str
    quantidade: int
    status: str
    nome_cliente: str
    data_entrega: date
    pecas_produzidas: int
    preco_unitario: float

class AlertaAtraso(BaseModel):
    id: Optional[UUID] = None
    nome_cliente: str
    data_entrega: date
    codigo_op: str
    criado_em: Optional[datetime] = None
    nome_peca: str

# --- API Input Models ---

class OrderCreate(BaseModel):
    nome_cliente: str
    numero_pedido: int
    data_pedido: Optional[date] = None
    preco_total: float
    data_entrega: date
    icms: float = 0.0
    previsao_entrega: Optional[date] = None
    # codigo_op will be generated by backend
    # status defaults to 'Pendente'

class PartCreate(BaseModel):
    nome_peca: str
    quantidade: int
    preco_unitario: float
    # Other fields inherited from Order or defaults

class PartsListCreate(BaseModel):
    codigo_op: str
    pecas: List[PartCreate]
